"""add booking_reference to bookings

Revision ID: 8b8e77181ce0
Revises: a21278f627b3
Create Date: 2025-12-20 21:48:28.054697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8e77181ce0'
down_revision: Union[str, Sequence[str], None] = 'a21278f627b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_reference', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_bookings_booking_reference'), 'bookings', ['booking_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_booking_reference'), table_name='bookings')
    op.drop_column('bookings', 'booking_reference')
    # ### end Alembic commands ###
