"""Add contact info and special_requests to bookings table

Revision ID: a21278f627b3
Revises: b99a331a2d81
Create Date: 2025-12-20 20:39:57.504604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a21278f627b3'
down_revision: Union[str, Sequence[str], None] = 'b99a331a2d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('special_requests', sa.String(500), nullable=True))
    op.add_column('bookings', sa.Column('contact_email', sa.String(100), nullable=False))
    op.add_column('bookings', sa.Column('contact_phone', sa.String(20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'contact_phone')
    op.drop_column('bookings', 'contact_email')
    # ### end Alembic commands ###
