"""Add is_active column to destinations table

Revision ID: ab1269c70db4
Revises: cdd87e0df36b
Create Date: 2025-12-20 17:13:47.019367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1269c70db4'
down_revision: Union[str, Sequence[str], None] = 'cdd87e0df36b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_destinations_is_active'), 'destinations', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_destinations_is_active'), table_name='destinations')
    op.drop_column('destinations', 'is_active')
    # ### end Alembic commands ###
