"""add missing columns to bookings table

Revision ID: b6a5b3471f48
Revises: 8b8e77181ce0
Create Date: 2025-12-20 22:05:40.799393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b6a5b3471f48'
down_revision: Union[str, Sequence[str], None] = '8b8e77181ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('number_of_travelers', sa.Integer(), nullable=False))
    op.drop_column('bookings', 'number_of_people')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('number_of_people', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'number_of_travelers')
    # ### end Alembic commands ###
